// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAoex7992Mpsn4c0vOIXViZt0BbC7X_ae8',
    appId: '1:268306723418:web:5749b8df99b4e2fa27de63',
    messagingSenderId: '268306723418',
    projectId: 'variety-app-85431',
    authDomain: 'variety-app-85431.firebaseapp.com',
    storageBucket: 'variety-app-85431.firebasestorage.app',
    measurementId: 'G-1R9BBWQ0G7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBlN5Iki56qKOMhTzWUE6-1NUBxt4OIvlg',
    appId: '1:268306723418:android:97482ae7263bbb2327de63',
    messagingSenderId: '268306723418',
    projectId: 'variety-app-85431',
    storageBucket: 'variety-app-85431.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAoex7992Mpsn4c0vOIXViZt0BbC7X_ae8',
    appId: '1:268306723418:web:d37fbbd1085c2c7127de63',
    messagingSenderId: '268306723418',
    projectId: 'variety-app-85431',
    authDomain: 'variety-app-85431.firebaseapp.com',
    storageBucket: 'variety-app-85431.firebasestorage.app',
    measurementId: 'G-4NH0F6DS7H',
  );
}
